### ISSUE TITLE
生成Contents.json文件 优化

### ISSUE THREAD

**Issue by LinMaris** [WuOtto/MacImagesetGenerator#2]
我使用的是下面这种方式, 不需要写那么多echo
```
cat << EOF  > ./$1/Contents.json

#文件内容

EOF
```
建议用sublime, 选择shell语言, 防止语法错误

**Comment by WuOtto** [comment]
`cat`命令很强大，新版本已经更新替换了`echo`，谢谢你的指导

IDE我用的`VS Code`，很好用，也推荐你试一下
